version: "3"
services:
  app:
    platform: linux/amd64 # for M1 Mac
    ports:
      - "3030:3000"
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - .:/var/www/html
