version: "3"
services:
  app:
    platform: linux/amd64 # for M1 Mac
    ports:
      - "3000:8080"
    build:
      context: ..
      dockerfile: docker_cloudrun/Dockerfile
#    environment:
#      - PORT=8080
